In [1]:
import pandas as pd 
import seaborn as sns 
import plotly.express as px
import matplotlib.pyplot as plt

ri = pd.read_csv("rba-dataset.csv")
ri

,index,Login Timestamp,User ID,Round-Trip Time [ms],IP Address,Country,Region,City,ASN,User Agent String,Browser Name and Version,OS Name and Version,Device Type,Login Successful,Is Attack IP,Is Account Takeover
0,0,43:30.8,-4.324480e+18,NaN,10.0.65.171,NO,-,-,29695,Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like ...,Firefox 20.0.0.1618,iOS 13.4,mobile,False,False,False
1,1,43:43.5,-4.324480e+18,NaN,194.87.207.6,AU,-,-,60117,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile 46.0.2490,Android 4.1,mobile,False,False,False
2,2,43:55.9,-3.284140e+18,NaN,81.167.144.58,NO,Vestland,Urangsvag,29695,Mozilla/5.0 (iPad; CPU OS 7_1 like Mac OS X) ...,Android 2.3.3.2672,iOS 7.1,mobile,True,False,False
3,3,43:56.2,-4.324480e+18,NaN,170.39.78.152,US,-,-,393398,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile WebView 85.0.4183,Android 4.1,mobile,False,False,False
4,4,43:59.4,-4.618850e+18,NaN,10.0.0.47,US,Virginia,Ashburn,398986,Mozilla/5.0 (Linux; U; Android 2.2) Build/NMA...,Chrome Mobile WebView 85.0.4183,Android 2.2,mobile,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,1048570,39:49.8,-1.289540e+18,NaN,78.91.142.173,NO,-,-,224,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_...,Chrome 73.0.3654,Mac OS X 10.14.6,desktop,True,False,False
1048571,1048571,39:49.9,-4.324480e+18,NaN,81.166.220.196,NO,Oslo County,Oslo,29695,Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 lik...,Chrome Mobile 81.0.4044,iOS 11.2.6,mobile,False,False,False
1048572,1048572,39:50.7,6.727963e+18,NaN,209.236.117.250,US,-,-,393398,Mozilla/5.0 (Linux; U; Android 2.2) AppleWebK...,Chrome Mobile 81.0.4044.1924,Android 2.2,mobile,False,True,False
1048573,1048573,39:51.7,-2.317850e+18,NaN,10.0.82.206,PL,-,-,205727,Mozilla/5.0 (iPhone; CPU iPhone OS 14_2_1 lik...,Chrome Mobile 81.0.4044,iOS 14.2.1,mobile,False,False,False
1048574,1048574,39:53.5,4.364920e+18,NaN,37.191.209.129,NO,Oslo County,Oslo,57963,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6...,Chrome 69.0.3497.17.19,Mac OS X 10.14.6,desktop,False,False,False

In [4]:
# This is to find the Number of total attacks attempts 

Total_attack_attempts = ri[ri['Is Attack IP'] == True]
Total_attack_attempts

,index,Login Timestamp,User ID,Round-Trip Time [ms],IP Address,Country,Region,City,ASN,User Agent String,Browser Name and Version,OS Name and Version,Device Type,Login Successful,Is Attack IP,Is Account Takeover
4,4,43:59.4,-4.618850e+18,NaN,10.0.0.47,US,Virginia,Ashburn,398986,Mozilla/5.0 (Linux; U; Android 2.2) Build/NMA...,Chrome Mobile WebView 85.0.4183,Android 2.2,mobile,False,True,False
5,5,44:05.2,-4.324480e+18,NaN,209.236.123.126,US,-,-,393398,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile WebView 85.0.4183,Android 4.1,mobile,False,True,False
22,22,44:40.2,9.133471e+18,NaN,38.135.39.102,US,-,-,393398,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile 51.0.2704,Android 4.1,mobile,False,True,False
52,52,45:13.7,-3.522290e+18,NaN,209.236.117.198,US,-,-,393398,Mozilla/5.0 (Mobile; Windows Phone 8.1; Andro...,Chrome Mobile 84.0.4147,Windows Phone 8.1,mobile,True,True,False
60,60,45:16.5,-6.623220e+18,NaN,170.82.7.240,BR,Sao Paulo,Artur Nogueira,266433,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6...,Chrome 69.0.3497.17.19,Mac OS X 10.14.6,desktop,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048549,1048549,39:35.4,-4.324480e+18,NaN,38.135.39.211,US,-,-,393398,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile 63.0.3239,Android 4.1,mobile,False,True,False
1048554,1048554,39:39.2,-6.866790e+18,511.0,10.0.9.4,NO,Oslo County,Oslo,207674,Mozilla/5.0 (Linux; U; Android 13.0; i phone X...,Opera Mobile 52.1.2254,Android 13.0,mobile,False,True,False
1048556,1048556,39:40.9,-4.324480e+18,NaN,176.104.176.250,PL,Lesser Poland,Lapanow,198377,Mozilla/5.0 (Mobile; LYF/F220B/LYF-F220B-003-...,Chrome Mobile 81.0.4044.1991,KaiOS 2.5,mobile,False,True,False
1048559,1048559,39:44.3,-8.179480e+18,NaN,209.236.125.252,US,-,-,393398,Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 lik...,Chrome Mobile 48.0.2564,iOS 11.2.6,mobile,True,True,False
1048572,1048572,39:50.7,6.727963e+18,NaN,209.236.117.250,US,-,-,393398,Mozilla/5.0 (Linux; U; Android 2.2) AppleWebK...,Chrome Mobile 81.0.4044.1924,Android 2.2,mobile,False,True,False

In [6]:
#This is the actual number of number of attacks

Total_attack_attempts['Is Attack IP'].value_counts()

Is Attack IP
True    104231
Name: count, dtype: int64

In [7]:
Total_attack_attempts['Country'].value_counts()

Country
US    74413
PL     8692
NO     5867
RO     3459
ID     2009
      ...
OM        1
SG        1
RS        1
BB        1
AZ        1
Name: count, Length: 114, dtype: int64

In [8]:
Total_attack_attempts['Region'].value_counts()

Region
-                     74737
Texas                  5757
Silesia                2919
Mazovia                2329
Bucuresti              2165
                      ...
Saint Andrew              1
Dubai                     1
West Sumatra              1
Parwan                    1
Chelyabinsk Oblast        1
Name: count, Length: 368, dtype: int64

In [12]:
#The number of successful attempts 
Total_success= ri[(ri['Login Successful'] == True) & (ri['Is Attack IP'] == True)]
Total_success

,index,Login Timestamp,User ID,Round-Trip Time [ms],IP Address,Country,Region,City,ASN,User Agent String,Browser Name and Version,OS Name and Version,Device Type,Login Successful,Is Attack IP,Is Account Takeover
52,52,45:13.7,-3.522290e+18,NaN,209.236.117.198,US,-,-,393398,Mozilla/5.0 (Mobile; Windows Phone 8.1; Andro...,Chrome Mobile 84.0.4147,Windows Phone 8.1,mobile,True,True,False
89,89,45:36.4,4.944981e+17,NaN,37.148.220.204,AU,-,-,60117,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile WebView 85.0.4183,Android 4.1,mobile,True,True,False
123,123,46:02.6,9.133471e+18,NaN,38.135.39.102,US,-,-,393398,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile 51.0.2704,Android 4.1,mobile,True,True,False
129,129,46:09.4,9.133471e+18,NaN,38.135.39.102,US,-,-,393398,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile 51.0.2704,Android 4.1,mobile,True,True,False
213,213,47:13.2,-4.796220e+17,NaN,87.248.28.16,NO,Innlandet,Gj√∏vik,29492,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6...,Chrome 86.0.4202,Mac OS X 10.14.6,desktop,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048396,1048396,37:34.9,-1.121430e+18,NaN,209.236.125.7,US,-,-,393398,Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 lik...,Chrome Mobile 81.0.4044.1943,iOS 11.2.6,mobile,True,True,False
1048444,1048444,38:12.3,-4.644430e+18,NaN,109.247.173.174,NO,Viken,Gullaug,29695,Mozilla/5.0 (iPhone; CPU iPhone OS 9_0_2 like...,Android 2.3.6,iOS 9.0.2,mobile,True,True,False
1048478,1048478,38:40.9,-1.121430e+18,NaN,209.236.125.7,US,-,-,393398,Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 lik...,Chrome Mobile 81.0.4044.1943,iOS 11.2.6,mobile,True,True,False
1048505,1048505,39:00.4,-2.179270e+18,NaN,10.0.11.235,NO,Viken,Brarud,500021,Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 lik...,Firefox 20.0.0.1850,iOS 11.2.6,mobile,True,True,False
1048559,1048559,39:44.3,-8.179480e+18,NaN,209.236.125.252,US,-,-,393398,Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 lik...,Chrome Mobile 48.0.2564,iOS 11.2.6,mobile,True,True,False

In [13]:
Total_success['Browser Name and Version'].value_counts()

Browser Name and Version
Chrome Mobile WebView 85.0.4183     6214
Chrome Mobile 81.0.4044             2968
Firefox 20.0.0.1618                 1598
Chrome Mobile 81.0.4044.1943        1474
Chrome 69.0.3497.17.19              1339
                                    ...
Chrome Mobile 81.0.4044.2257           1
Chrome Mobile iOS 66.0.3359.3471       1
Chrome 79.0.3945.192.201               1
Chrome Mobile 18.0.1025.2732           1
Firefox iOS 1.0                        1
Name: count, Length: 422, dtype: int64

In [14]:
Total_success['OS Name and Version'].value_counts()

OS Name and Version
iOS 11.2.6          9513
Android 4.1         4166
iOS 14.2.1          2615
Mac OS X 10.14.6    2254
Android 2.2         2157
                    ...
Mac OS X 10.9          1
iOS 2.5.1              1
iOS 8.1.3              1
Android 5.2.2          1
iOS 8.3                1
Name: count, Length: 111, dtype: int64

In [15]:
Total_success['Device Type'].value_counts()

Device Type
mobile     29812
desktop     3408
tablet       392
unknown        2
Name: count, dtype: int64